image: gjhenrique/blog

stages:
  - blog

pages:
  stage: jekyll
  before_script:
    - bundle install
    - pushd syntax-extractor && npm install && popd
  script:
    - emacs -batch -q -l export.el -f org-publish-all
    - node syntax-extractor/index.js darktooth
    - JEKYLL_ENV=production jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
