image: mwallasch/docker-ruby-node

stages:
  - cv
  - blog

cv:
  image: gjhenrique/blog
  stage: cv
  before_script:
    - cd cv
    - npm install
  script:
    - npm run all
    - cd ..
  artifacts:
    paths:
      - cv
  only:
    - master

pages:
  stage: blog
  before_script:
    - gem install jekyll
    - gem install jekyll-paginate
    - gem install jekyll-assets
    - gem install font-awesome-sass
    - pushd syntax-extractor && npm install && popd
  script:
    - node syntax-extractor/index.js
    - JEKYLL_ENV=production jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master


