# Site settings
title: "(blog 'zezin)"
rss_title: gjhenrique - Zezin
description: "A simple blog"
url: "https://gjhenrique.com"
author:
  name: "Guilherme Henrique"
  email: "gjhenrique@gmail.com"
  url: "https://gjhenrique.com"

# Build settings
github: https://github.com/gjhenrique
gitlab: https://gitlab.com/gjhenrique
markdown: kramdown
source: .
destination: ./_site
permalink: /:title.html
paginate: 8
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-assets
exclude: [syntax-extractor, org, vendor]

assets:
  compression: true
  gzip: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
