# Site settings
title: Blog of gjhenrique
description: "A simple blog"
url: "http://gjhenrique.com"
author:
  name: "Guilherme Henrique"
  email: "gjhenrique@gmail.com"
  url: "http://gjhenrique.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
github: https://github.com/gjhenrique
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
gems: ["jekyll-paginate"]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
