---
name: Publish pages
on: [push]
jobs:
  generate-org-images:
    runs-on: ubuntu-latest
    container:
      image: silex/emacs:28.1-alpine-ci
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: apk update && apk add graphviz ttf-freefont

      - name: Generate images
        run: emacs -batch -q -l export.el -f org-publish-with-different-timestamp-directory

      - uses: actions/upload-artifact@v3
        with:
          name: posts
          path: |
            content/posts
            static/res
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: generate-org-images
    container:
      image: klakegg/hugo:ext-alpine
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CFP_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CFP_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: posts

      - name: Install wrangler
        run: apk update && apk add yarn && yarn global add wrangler

      - name: Call hugo to generate final asset
        run: hugo

      - name: Publish to Clouflare Pages
        run: wrangler pages publish --project-name=blog public
